### ISSUE TITLE
bug(#350 regression): nRF52 companion variants fail to link — CrashLog.cpp not compiled (missing diagnostics/ src filter)

### ISSUE THREAD

**Issue by Strycher** [OffbandMesh/meshcore-firmware#475]
**Regression from #350** (landed in PR #474, `b23c807e`). Found by DarkLynx while verifying #370 — **not** a #370 issue (#370's `main.cpp`/`rak4631.ini` are byte-identical to base).

**Cause:** #350 moved `CrashLog.cpp` → `src/helpers/diagnostics/`, and #377 wired `crashLog*` calls into `examples/companion_radio/main.cpp` for **all** nRF52 companions (`#if defined(NRF52_PLATFORM) && !defined(OFFBAND_OBSERVER)`). But the `+<helpers/diagnostics/*.cpp>` src-filter add only went to `rak3401` (#376) + the ESP32 observer variants (#350). So on **every other nRF52 companion variant**, `CrashLog.cpp` isn't compiled → `undefined reference to offband::crashLogf / crashLogBegin / crashLogTick / crashLogSetResetReasonHook`.

**Verified:** `RAK_4631_companion_radio_usb` link FAILS (DarkLynx). My #350 merge-verify only built `RAK_3401_companion_radio_usb` (which has the filter) — the subset missed it. My fault.

**Scope (audit):** ~33 nRF52 companion variants broken — every nRF52 companion except `rak3401`. ESP32 companions are unaffected (they don't call `crashLog*` — it's nRF52-gated).

**Fix:** add `+<helpers/diagnostics/*.cpp>` to `arduino_base.build_src_filter` (the common root — `esp32_base`/`nrf52_base`/`rp2040_base` all `extends = arduino_base`). One line fixes all platforms; the linker `--gc-sections` drops `CrashLog.cpp` where it's not called (no RAM/flash cost on non-using envs; CrashLog has no forcing constructor). Verified with a diverse build sample before landing.

Parent: #350.

**Comment by Strycher** [comment]
Fixed by adding `+<helpers/diagnostics/*.cpp>` to `arduino_base.build_src_filter` (commit f3b74d34). Verified across every chip family (11 envs): ESP32-S3/C3/C6/classic, nRF52 (direct + intermediate-base), RP2040, STM32 — including the confirmed-broken RAK_4631 + GAT562. Merging to firmware-base now.
