### PR TITLE
fix(#89): exclude SerialBLEInterface.cpp from Xiao_S3_WIO_companion_radio_usb

### LINKED ISSUE #86: chore: provision XIAO ESP32-S3 "WSMJ898 KETT" — flash Xiao_S3_WIO_companion_radio_usb + verify
## Summary
Provision a newly-attached Seeed XIAO ESP32-S3 (Wio-SX1262 kit) as a MeshCore companion radio: flash the `Xiao_S3_WIO_companion_radio_usb` env (USB-CDC companion) and verify it boots. The owner will set the advert name **"WSMJ898 KETT"** via the companion app *after* flashing — naming is not part of the flash.

## Device
- **Port:** COM22 (identified by USB-descriptor cross-check against the gitignored `hardware-devices.yaml` registry; positively the only unregistered S3-class device attached).
- **USB class:** VID:PID `2886:0059` (Seeed factory-firmware composite-descriptor state — fresh/unregistered).
- **MAC / SER:** captured into `hardware-devices.yaml` (gitignored, per-host) — intentionally not duplicated here (redaction discipline, CLAUDE-BASE).
- **Target env:** `Xiao_S3_WIO_companion_radio_usb` (WIO variant; only ESP32-S3 XIAO variant in tree; matches prior XIAO flashes).

## Plan
1. File issue + Citadel task + claim (file-first). ✓
2. Reserve + add device entry to `hardware-devices.yaml` (gitignored) via `pio-flash` bootstrap (authorized `esptool read_mac`).
3. Enter ESP32-S3 bootloader — likely the 1200-baud DFU trick (device is in factory composite-descriptor state, same as `xiao-bench-1`).
4. **Flash via canonical `scripts/pio-flash` (Tier-2 — explicit per-flash approval).** Raw esptool is hook-blocked.
5. Verify: USB-CDC / serial confirms companion firmware boots.

## Acceptance criteria
- [ ] Device registered in `hardware-devices.yaml` (MAC, VID:PID list, discriminators).
- [ ] `Xiao_S3_WIO_companion_radio_usb` flashed successfully to the COM22 device.
- [ ] Serial/USB-CDC verification confirms companion firmware running.
- [ ] No other device touched — ST-P (COM10), hv3-bench (COM6), and **desk_command_center (COM3, foreign — never touch)** all untouched.

## the standards
- **Flash = Tier-2:** explicit per-action approval each time. Rollback: re-flash; capture a pre-flash backup read if feasible (factory state has no prior backup).
- Canonical flash path only (`scripts/pio-flash`); raw esptool/curl blocked by hooks.
- No code change / no PR — gitignored registry edit only.

Priority: P2

### LINKED ISSUE #89: bug: Xiao_S3_WIO_companion_radio_usb fails to build — NimBLEDevice.h (regression from #288)
## Bug
`pio run -e Xiao_S3_WIO_companion_radio_usb` fails to compile:
```
src/helpers/esp32/SerialBLEInterface.h:4: fatal error: NimBLEDevice.h: No such file or directory
```

## Root cause
The #288 NimBLE migration (`562347be`, `b25bc3fd`) added the NimBLE-Arduino lib **only to the `_ble` env**, but this `_usb` env still compiles `SerialBLEInterface.cpp` via the greedy `build_src_filter += <helpers/esp32/*.cpp>`. The USB build never *uses* BLE — `main.cpp:56` gates the BLE interface behind `defined(BLE_PIN_CODE)`, which this env does not set. So the file is compiled but never referenced. Full analysis: Strycher/Crosswire#86 (comment).

## Fix (verified safe)
Add `-<helpers/esp32/SerialBLEInterface.cpp>` to `Xiao_S3_WIO_companion_radio_usb`'s `build_src_filter`. No missing symbol (USB build never references it).

## Scope
This env only — needed to unblock device provisioning (#86). The same regression on `heltec_v3`/`v4` + the `_serial`/`_wifi` companion envs is tracked separately ("fix properly later").

## Acceptance
- [ ] `pio run -e Xiao_S3_WIO_companion_radio_usb` builds clean.

### PR DESCRIPTION
**Pull request by Strycher**
## Summary
Fixes the #288 NimBLE-migration build regression for the **`Xiao_S3_WIO_companion_radio_usb`** env. The greedy `+<helpers/esp32/*.cpp>` filter pulled `SerialBLEInterface.cpp` (which `#include <NimBLEDevice.h>`) into the USB build, but NimBLE is only a `lib_dep` of the `_ble` env → `fatal error: NimBLEDevice.h: No such file or directory`.

The USB companion never uses BLE — `examples/companion_radio/main.cpp` only instantiates `SerialBLEInterface` under `defined(BLE_PIN_CODE)`, which the `_usb` env does not define. So excluding that one file from this env's `build_src_filter` is safe.

## Change
One line in the `_usb` env's per-env `build_src_filter`:
```
-<helpers/esp32/SerialBLEInterface.cpp>
```

## Validation
- ✅ `pio run -e Xiao_S3_WIO_companion_radio_usb` builds green (Flash 18.5%).
- ✅ **End-to-end verified:** this firmware was flashed to a device (WSMJ898 KETT) and is fully operational — companion-API + LoRa radio confirmed (closed #86).
- ✅ `pio run -e Xiao_S3_WIO_companion_radio_ble` still builds green (Flash 25%) — proves the exclusion is **per-env scoped** and does not affect the BLE build.

## Adversarial review (Gemini 2.5 Pro)
Ran the binding pre-PR review. It raised a BLOCKER claiming the exclusion sits in a "shared section" and would leak to `_ble`. **Adjudicated as a false positive:** the exclusion is at line 144, inside `[env:Xiao_S3_WIO_companion_radio_usb]` (130–152); the `_ble` env has its own filter; the base `[Xiao_S3_WIO]` filter is untouched. Confirmed structurally **and empirically** (green `_ble` build above). Gemini only had the diff, not the full `.ini`.

## Scope
This env only. The same regression on `heltec_v3`/`v4` + the `_serial`/`_wifi` companion envs is tracked separately in #90 ("fix properly later").

Closes #89.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Strycher** [comment]
Closing as superseded, verified: this PR's exact change — `-<helpers/esp32/SerialBLEInterface.cpp>` with the same #89 comment — is already in firmware-base at variants/xiao_s3_wio/platformio.ini:145, and the env builds green in the required CI matrix. No unique content remains. — WhiteFalcon (session cb12cdd2), pre-release triage per owner
