### ISSUE TITLE
bug: Xiao_S3_WIO_companion_radio_usb fails to build — NimBLEDevice.h (regression from #288)

### ISSUE THREAD

**Issue by Strycher** [OffbandMesh/meshcore-firmware#89]
## Bug
`pio run -e Xiao_S3_WIO_companion_radio_usb` fails to compile:
```
src/helpers/esp32/SerialBLEInterface.h:4: fatal error: NimBLEDevice.h: No such file or directory
```

## Root cause
The #288 NimBLE migration (`562347be`, `b25bc3fd`) added the NimBLE-Arduino lib **only to the `_ble` env**, but this `_usb` env still compiles `SerialBLEInterface.cpp` via the greedy `build_src_filter += <helpers/esp32/*.cpp>`. The USB build never *uses* BLE — `main.cpp:56` gates the BLE interface behind `defined(BLE_PIN_CODE)`, which this env does not set. So the file is compiled but never referenced. Full analysis: Strycher/Crosswire#86 (comment).

## Fix (verified safe)
Add `-<helpers/esp32/SerialBLEInterface.cpp>` to `Xiao_S3_WIO_companion_radio_usb`'s `build_src_filter`. No missing symbol (USB build never references it).

## Scope
This env only — needed to unblock device provisioning (#86). The same regression on `heltec_v3`/`v4` + the `_serial`/`_wifi` companion envs is tracked separately ("fix properly later").

## Acceptance
- [ ] `pio run -e Xiao_S3_WIO_companion_radio_usb` builds clean.
