### PR TITLE
fix(#89): exclude SerialBLEInterface.cpp from Xiao_S3_WIO USB companion

### LINKED ISSUE #89: bug: Xiao_S3_WIO_companion_radio_usb fails to build — NimBLEDevice.h (regression from #288)
## Bug
`pio run -e Xiao_S3_WIO_companion_radio_usb` fails to compile:
```
src/helpers/esp32/SerialBLEInterface.h:4: fatal error: NimBLEDevice.h: No such file or directory
```

## Root cause
The #288 NimBLE migration (`562347be`, `b25bc3fd`) added the NimBLE-Arduino lib **only to the `_ble` env**, but this `_usb` env still compiles `SerialBLEInterface.cpp` via the greedy `build_src_filter += <helpers/esp32/*.cpp>`. The USB build never *uses* BLE — `main.cpp:56` gates the BLE interface behind `defined(BLE_PIN_CODE)`, which this env does not set. So the file is compiled but never referenced. Full analysis: Strycher/Crosswire#86 (comment).

## Fix (verified safe)
Add `-<helpers/esp32/SerialBLEInterface.cpp>` to `Xiao_S3_WIO_companion_radio_usb`'s `build_src_filter`. No missing symbol (USB build never references it).

## Scope
This env only — needed to unblock device provisioning (#86). The same regression on `heltec_v3`/`v4` + the `_serial`/`_wifi` companion envs is tracked separately ("fix properly later").

## Acceptance
- [ ] `pio run -e Xiao_S3_WIO_companion_radio_usb` builds clean.

### PR DESCRIPTION
**Pull request by Strycher**
## fix(#89): Xiao_S3_WIO USB companion NimBLE build regression

Closes #89.

`Xiao_S3_WIO_companion_radio_usb` failed with `fatal error: NimBLEDevice.h: No such file or directory` — the #288 NimBLE migration added NimBLE only to `_ble` envs, but the USB env still greedy-compiled `helpers/esp32/SerialBLEInterface.cpp` without the dep. The USB companion never uses BLE (gated on `BLE_PIN_CODE`, undefined here), so the fix excludes that NimBLE-only file from the env's `build_src_filter`.

1-line change; build verified green on current firmware-base (Flash 18.6%). Re-applies the original fix (`d89561c4`) that had been stranded on an unmerged stale branch.

Related (separate, tracked): **#90** (non-BLE serial/wifi envs across boards), **#199** (xiao_c6 BLE missing NimBLE dep).

### CODE REVIEW

**Comment by Strycher** [comment]
Human merge approval received (Ben, 2026-06-24). Enabling auto-merge (--rebase) per DW flow.
